[package]
name = "tsplay"
version = "0.1.0"
authors = ["Cesbo Developers Team"]
edition = "2018"

[dependencies]
clap = "~2.33.3"
serde = { version = "1.0", features = ["derive"] }
anyhow = "~1.0.44"
serde_json = "~1.0.67"
tokio-uring = "~0.1.0"
